[build]
  command = "echo 'No build command needed for static site' && cp -r .netlify/functions public/functions"
  publish = "public"
  functions = ".netlify/functions"

[functions]
  node_bundler = "esbuild" # Optional: Use esbuild to bundle Node.js functions

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200